name: Bash linter
on:
  push:
    branches:
      - main
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
