name: linter
on:
  pull_request:
    paths:
      - '**/*.sh'
  push:
    paths:
      - '**/*.sh'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
